# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\ui_fault_injection.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Fault(object):
    def setupUi(self, Fault):
        Fault.setObjectName("Fault")
        Fault.resize(291, 260)
        self.groupBox = QtWidgets.QGroupBox(Fault)
        self.groupBox.setGeometry(QtCore.QRect(20, 20, 251, 181))
        self.groupBox.setObjectName("groupBox")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setGeometry(QtCore.QRect(10, 50, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setGeometry(QtCore.QRect(10, 110, 54, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 140, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.modeBox = QtWidgets.QComboBox(self.groupBox)
        self.modeBox.setGeometry(QtCore.QRect(130, 50, 111, 22))
        self.modeBox.setObjectName("modeBox")
        self.erBox = QtWidgets.QComboBox(self.groupBox)
        self.erBox.setGeometry(QtCore.QRect(130, 80, 111, 22))
        self.erBox.setObjectName("erBox")
        self.exe_timesBox = QtWidgets.QComboBox(self.groupBox)
        self.exe_timesBox.setGeometry(QtCore.QRect(130, 110, 111, 22))
        self.exe_timesBox.setObjectName("exe_timesBox")
        self.bfmBox = QtWidgets.QComboBox(self.groupBox)
        self.bfmBox.setGeometry(QtCore.QRect(130, 140, 111, 22))
        self.bfmBox.setObjectName("bfmBox")
        self.pushButton = QtWidgets.QPushButton(Fault)
        self.pushButton.setGeometry(QtCore.QRect(200, 220, 75, 23))
        self.pushButton.setObjectName("pushButton")

        self.retranslateUi(Fault)
        QtCore.QMetaObject.connectSlotsByName(Fault)

    def retranslateUi(self, Fault):
        _translate = QtCore.QCoreApplication.translate
        Fault.setWindowTitle(_translate("Fault", "故障注入配置"))
        self.groupBox.setTitle(_translate("Fault", "故障注入"))
        self.label.setText(_translate("Fault", "模 式："))
        self.label_2.setText(_translate("Fault", "错误率："))
        self.label_3.setText(_translate("Fault", "次 数："))
        self.label_4.setText(_translate("Fault", "翻转类型："))
        self.pushButton.setText(_translate("Fault", "确定"))
